dist: trusty
sudo: required
language: java
jdk:
  - oraclejdk8
env:
  - TRAVIS_NODE_VERSION="12"
cache:
  directories:
    - $HOME/.m2
    - node_modules
install: true

before_install:
  - sudo apt-get update
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g rimraf
  
before_script:
  - "export NODE_BIN=`nvm which $TRAVIS_NODE_VERSION`"
  - "export NODE_PATH=`dirname $NODE_BIN`"
  - "export CI=true"
  
script:
  - set -e

  - echo 'Installing...' && echo -en 'travis_fold:start:install\\r'
  - node common/scripts/install-run-rush.js install
  - echo -en 'travis_fold:end:install\\r'

  - echo 'Building...' && echo -en 'travis_fold:start:build\\r'
  - node common/scripts/install-run-rush.js rebuild --verbose
  - echo -en 'travis_fold:end:build\\r'
  
  - ./gradlew build

addons:
  ssh_known_hosts:
    - repo.maven.org