permissions:
- role: ADMIN
  privileges:
  - GENERAL_ADMIN
  - FOLDER_READ
  - FOLDER_CREATE
  - FOLDER_DELETE
  - DASHBOARD_READ
  - DASHBOARD_EDIT
  - DASHBOARD_DELETE
- role: ANONYMOUS
  privileges:
  - DASHBOARD_READ
