authorities:
- role: GENERAL_ADMIN
  permissions:
  - FOLDER_READ
  - FOLDER_CREATE
  - FOLDER_DELETE
  - DASHBOARD_READ
  - DASHBOARD_EDIT
  - DASHBOARD_DELETE
- role: ANONYMOUS
  permissions:
  - DASHBOARD_READ
