version: '3.7'
services:


  sprout-server:
    image: savantly/sprout-server
    container_name: fm-sprout-server
    ports:
      - 8080:8080
    volumes:
    - ./build/libs:/sprout/modules

  webapp:
    image: savantly/sprout-webapp
    container_name: fm-sprout-webapp
    ports:
      - 3000:3000
    environment: 
      - SPROUT_API_URL=http://fm-sprout-server:8080
    depends_on: 
      - sprout-server
